<a href="https://colab.research.google.com/github/shivanikush/PyTorch_basics/blob/main/PyTorch_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>



*   Tensor Basic
*   create, Operations, Numpy,GPU Support

---


*   Autograd
     linear regression example


---


*   Training Loop with model, loss and Optimizer
      typical PyTorch training pipeline


---


*   Neural Network
      GPU, Datasets, Dataloader, Transforms and Evaluation


---


*   Convolution Neural Network
      save/load model






Everything in PyTorch is tensor operation. 
Atensor is a multi dimensional matrix containing elements of a single datatype.

In [2]:
import torch

# torch.empty(size): uninitialized
x = torch.empty(1) #scalar
print("empty[1]:", x)
x = torch.empty(3) #vector
print("empty[3]:",x)
x = torch.empty(2,3) #matrix
print("empty[2,3]",x)
x = torch.empty(2,2,3) #tensor, 3 dimension
#x = torch,empty(2,2,2,3) #tensor 4 dimension
print("empty[2,2,3]",x)


#torch.rand(size): random numbers [0,1]
x = torch.rand(5,3)
print("rand(5,3)", x)


#torch.zeros(size) fill with 0
#torch.ones(size), fill with 1
x = torch.zeros(5,3)
print("zeros",x)




empty[1]: tensor([-4.4069e-24])
empty[3]: tensor([6.5764e-35, 0.0000e+00, 6.5761e-35])
empty[2,3] tensor([[ 6.5785e-35,  0.0000e+00, -4.4069e-24],
        [ 4.5836e-41,  8.9683e-44,  0.0000e+00]])
empty[2,2,3] tensor([[[6.5778e-35, 0.0000e+00, 6.5799e-35],
         [0.0000e+00, 8.9683e-44, 0.0000e+00]],

        [[1.1210e-43, 0.0000e+00, 6.5761e-35],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])
rand(5,3) tensor([[0.2709, 0.0073, 0.9789],
        [0.2460, 0.3905, 0.3284],
        [0.9611, 0.7191, 0.3719],
        [0.5092, 0.7947, 0.8173],
        [0.8856, 0.6283, 0.6605]])
zeros tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
print("size", x.size)
print("shape", x.shape)

size <built-in method size of Tensor object at 0x7fc6783b85e0>
shape torch.Size([5, 3])


In [4]:
#check data type
print("datatype", x.dtype)

datatype torch.float32


In [5]:
x= torch.zeros(5,3, dtype = torch.float16)
print(x.dtype)

torch.float16


In [6]:
#construct from data
x = torch.tensor([4,5,2])
print(x,x.dtype)

tensor([4, 5, 2]) torch.int64


In [8]:
#tensor requires_grad argument
#this will tell pytorch that it will need to calculate the gradients for this tensor
#later in the optimization steps
x = torch.tensor([4.5,5,6], requires_grad = True)
print(x)

tensor([4.5000, 5.0000, 6.0000], requires_grad=True)


**Operations with Tensor\\**

In [11]:
x = torch.ones(3,3)
y= torch.rand(3,3)

#element - wise addition
z = x + y
#torch.add(x,y)
#in-place addition; everything with a trailing underscore is an in-place operation
#it will modify the variable
#y.add_(x)

print(x)
print(y)
print(z)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1.0842, 1.0682, 1.2099],
        [1.5867, 1.9978, 1.8625],
        [1.5735, 1.7006, 1.5822]])
tensor([[1.0842, 1.0682, 1.2099],
        [1.5867, 1.9978, 1.8625],
        [1.5735, 1.7006, 1.5822]])


In [12]:
#subtraction
x = torch.rand(2,2)
y = torch.rand(2,2)

torch.sub(x,y)

#multiplication
torch.mul(x,y)

#division
torch.div(x,y)

tensor([[4.4817e+00, 9.0374e+00],
        [2.0594e-03, 4.3522e-02]])

In [20]:
#slicing
m = torch.rand(5,3)
print(m)
print("[:0]", m[:,0]) #all rows, column 0
print("[1:]", m[1,:]) #row 1, all column
print("[1,1]", m[1,1]) #element at 1,1
#get the actual value if only 1 element in your tensor

print("x[1,1].item()", m[1,1].item())

tensor([[0.2776, 0.6355, 0.4681],
        [0.1704, 0.9394, 0.0386],
        [0.1074, 0.8477, 0.2531],
        [0.7135, 0.5597, 0.6817],
        [0.8250, 0.9739, 0.6709]])
[:0] tensor([0.2776, 0.1704, 0.1074, 0.7135, 0.8250])
[1:] tensor([0.1704, 0.9394, 0.0386])
[1,1] tensor(0.9394)
x[1,1].item() 0.9393526911735535


In [23]:
#Reshape with torch.view()
n = torch.randn(4,4)
p = n.view(16)
z = p.view(-1,8) #size -1 is inferred from other dimension
#if -1 pytorch will automatically determine the accurate size
print(n.size(), p.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


**NumPy**

---

  Converting a torch tensor into numpy array and vice versa.

In [26]:
a = torch.ones(5)
print(a)


#torch ---> numPy with .numpy()
b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [30]:
#Caareful if the tensor is on the CPU (!not GPU)
#both object will share the same memory location, so changing one will cause the other one to change
a.add_(1)
print("a:",a)
print("b:",b)

a: tensor([4., 4., 4., 4., 4.])
b: [4. 4. 4. 4. 4.]


In [33]:
#numpy --> torch with .from_numpy(x), torch.tensor() copy it
import numpy as np
d = np.ones(5)
c = torch.from_numpy(d)
g = torch.tensor(d)
print(d)
print(c)
print(g)


#----------------------------
#again be careful while modifying
d +=1
print("!",d)
print("2",c)
print("3",g)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
! [2. 2. 2. 2. 2.]
2 tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
3 tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


**GPU Support**


---

By default all tensors are created on CPU, we can move them to GPU (if available) or directly create them on GPU

In [34]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.rand(2,2).to(device) #Move tensor to GPU
#x = x.to("cpu")
#x = x.to("cuda")


x = torch.rand(2,2, device = device)  #or directly create them on GPU

**AutoGrad**


---

provide automatice differentiation for all operations on Tensors.  Torch.autograd is an engine for computing vector-Jacobian product. It computes partial differentiation while applying chain rule.


Set 
requires_grad = True

In [35]:
#requires_grad = True --> track all operations on Tensor

x = torch.randn(3,requires_grad = True)
y = x + 2

#y was created as result of an operation, so it has a grad_fn attribute
#grad_fn = references function that has created a tensor
print(x) #created by user, grad_fn is None
print(y)
print(y.grad_fn)

tensor([0.2269, 0.8693, 0.6450], requires_grad=True)
tensor([2.2269, 2.8693, 2.6450], grad_fn=<AddBackward0>)


In [37]:
#performingmore operations on y
z = y * y *3
print(z)
z = z.mean()
print(z)


tensor([14.8776, 24.6983, 20.9882], grad_fn=<MulBackward0>)
tensor(20.1880, grad_fn=<MeanBackward0>)


In [38]:
#computing the gradient with backpropagation
#when we finish our computation we can call .backward() and have all gradients computed automatically
#the gradients from this tensor will be accumulated into .grad attribute
#it is a partial derivative of a function w.r.t tensor


z.backward()
print(x.grad) #dz/dx

""" backward accumulates the gradient for this tensor into .grad attribute 
!!! we need to be careful while optimization  ! optimizer.zero_grad() """

tensor([4.4538, 5.7386, 5.2900])


' backward accumulates the gradient for this tensor into .grad attribute \n!!! we need to be careful while optimization  ! optimizer.zero_grad() '